[package]
name = "thing-go"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.3.0"
lib-thing = { path = "../lib-thing" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
